on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: A job to run govulncheck
    steps:
      - name: golang-govulncheck-action
        uses: bkessler-go/prototype-govulncheck-action@v1.3
        with:
          check-latest: true
          cache: false

